export const SUPABASE_URL = 'https://ihbrwsncysnzdjfkaawe.supabase.co'
export const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloYnJ3c25jeXNuemRqZmthYXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDE3MjAzNTUsImV4cCI6MjAxNzI5NjM1NX0.vwuSl6RZ_d98bUMCxmAs8_j_GviFLYMmBQF5E78JdDA'
